[sam4h]
sam4h-srv ansible_host=192.168.100.100 ansible_user=sysadmin

[storage_emulators]
emu-stor-01 ansible_host=192.168.100.101 ansible_user=sysadmin
emu-stor-02 ansible_host=192.168.100.102 ansible_user=sysadmin

[all:vars]
ansible_connection=ssh
ansible_ssh_private_key_file=~/.ssh/id_ed25519